"use client";

import { useMemo, useState } from "react";
import {
  Bell, ChevronRight, CircleHelp, CreditCard, Filter,
  LayoutGrid, LifeBuoy, Menu, MoreHorizontal, Plus, Search, Settings, Sparkles, Users,
  X, Zap
} from "lucide-react";

type Lead = { id: string; name: string; company: string; value: string; initials: string; color: string; note: string };
const leads: Record<string, Lead[]> = {
  New: [
    { id: "l1", name: "Cameron Williamson", company: "Northstar Labs", value: "$18,400", initials: "CW", color: "#d9e9df", note: "Referred by Rachel" },
    { id: "l2", name: "Brooklyn Simmons", company: "Figma Inc.", value: "$12,800", initials: "BS", color: "#eadcf2", note: "Inbound · 2 hours ago" },
    { id: "l3", name: "Esther Howard", company: "Lattice", value: "$9,600", initials: "EH", color: "#f4dfca", note: "Product-led signup" },
  ],
  Qualified: [
    { id: "l4", name: "Wade Warren", company: "Vercel", value: "$24,000", initials: "WW", color: "#cfe4ee", note: "Demo booked for Fri" },
    { id: "l5", name: "Jenny Wilson", company: "Intercom", value: "$21,200", initials: "JW", color: "#e8dfc9", note: "Needs security review" },
  ],
  Proposal: [
    { id: "l6", name: "Robert Fox", company: "Notion", value: "$42,000", initials: "RF", color: "#e4dcf5", note: "Proposal viewed 3×" },
    { id: "l7", name: "Kristin Watson", company: "Linear", value: "$16,800", initials: "KW", color: "#f2d7da", note: "Decision next week" },
  ],
  Won: [
    { id: "l8", name: "Guy Hawkins", company: "Arc Browser", value: "$28,400", initials: "GH", color: "#d7f2e4", note: "Closed 2 days ago" },
    { id: "l9", name: "Dianne Russell", company: "Stripe", value: "$31,500", initials: "DR", color: "#d8e8f4", note: "Onboarding started" },
  ],
};

const nav = [{ label: "Overview", icon: LayoutGrid }, { label: "Pipeline", icon: Zap }, { label: "Contacts", icon: Users }, { label: "Billing", icon: CreditCard }];

export default function Home() {
  const [active, setActive] = useState("Pipeline");
  const [search, setSearch] = useState("");
  const [showAdd, setShowAdd] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const visibleLeads = useMemo(() => Object.fromEntries(Object.entries(leads).map(([stage, items]) => [stage, items.filter((lead) => `${lead.name} ${lead.company}`.toLowerCase().includes(search.toLowerCase()))])), [search]);

  return <main className="min-h-screen lg:flex">
    <aside className={`${mobileNav ? "flex" : "hidden"} fixed inset-0 z-20 w-full flex-col bg-[#fbfcfa] px-5 py-6 lg:relative lg:flex lg:w-[252px] lg:flex-none lg:px-6`}>
      <div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-xl bg-[#172026] text-sm font-bold text-white">p</span><span className="font-['Space_Grotesk'] text-[20px] font-bold tracking-[-.04em]">pipeline</span></div><button onClick={() => setMobileNav(false)} className="rounded-lg p-2 hover:bg-[#eef2ef] lg:hidden"><X size={20}/></button></div>
      <div className="mt-10 text-[11px] font-bold uppercase tracking-[.12em] text-[#a0aaa7]">Workspace</div>
      <nav className="mt-3 space-y-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileNav(false); }} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-[14px] font-semibold transition-all duration-300 ${active === label ? "bg-[#d7f2e4] text-[#20784e]" : "text-[#65716f] hover:bg-[#eef2ef] hover:text-[#172026]"}`}><Icon size={18} strokeWidth={1.8}/>{label}{label === "Pipeline" && <span className="ml-auto rounded-md bg-white/70 px-2 py-0.5 text-[11px] text-[#3b8c66]">9</span>}</button>)}</nav>
      <div className="mt-9 text-[11px] font-bold uppercase tracking-[.12em] text-[#a0aaa7]">Manage</div>
      <nav className="mt-3 space-y-1"><button className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-[14px] font-semibold text-[#65716f] hover:bg-[#eef2ef] hover:text-[#172026]"><Settings size={18} strokeWidth={1.8}/>Settings</button><button className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-[14px] font-semibold text-[#65716f] hover:bg-[#eef2ef] hover:text-[#172026]"><LifeBuoy size={18} strokeWidth={1.8}/>Help center</button></nav>
      <div className="mt-auto rounded-2xl bg-[#172026] p-4 text-white"><div className="mb-3 grid h-8 w-8 place-items-center rounded-lg bg-[#d7f2e4] text-[#20784e]"><Sparkles size={16}/></div><p className="text-sm font-semibold">Unlock your momentum</p><p className="mt-1 text-xs leading-5 text-[#aab9b3]">Automate the busywork and close more deals.</p><button className="mt-4 flex items-center gap-1 text-xs font-bold text-[#c8f2dc] hover:text-white">Explore Pro <ChevronRight size={14}/></button></div>
    </aside>
    <section className="min-w-0 flex-1"><header className="flex h-[72px] items-center justify-between border-b border-[var(--line)] bg-[#fbfcfa] px-5 sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileNav(true)} className="rounded-lg p-2 hover:bg-[#eef2ef] lg:hidden"><Menu size={20}/></button><div className="text-sm text-[#718087]">Workspace <ChevronRight className="mx-1 inline" size={14}/><span className="font-semibold text-[#172026]">{active}</span></div></div><div className="flex items-center gap-2 sm:gap-5"><button className="hidden items-center gap-2 text-sm font-semibold text-[#718087] hover:text-[#172026] sm:flex"><CircleHelp size={18}/>Support</button><button className="relative rounded-lg p-2 text-[#718087] hover:bg-[#eef2ef] hover:text-[#172026]"><Bell size={18}/><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-[#ee866c]"/></button><div className="h-8 w-px bg-[var(--line)]"/><div className="grid h-8 w-8 place-items-center rounded-full bg-[#edc1b4] text-xs font-bold">AM</div></div></header>
    {active === "Billing" ? <BillingWorkspace /> : <div className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 lg:px-12"><div className="fade-up flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-semibold text-[#2d9766]">Monday, June 24, 2024</p><h1 className="font-['Space_Grotesk'] text-[32px] font-bold tracking-[-.045em] sm:text-[40px]">Good morning, Alex <span aria-hidden="true">✦</span></h1><p className="mt-2 text-[15px] text-[#718087]">Here&apos;s what&apos;s happening with your pipeline today.</p></div><button onClick={() => setShowAdd(true)} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#172026] px-4 text-sm font-bold text-white shadow-[0_5px_15px_rgba(23,32,38,.12)] transition-transform hover:-translate-y-0.5 hover:bg-[#2c3b42]"><Plus size={17}/> Add lead</button></div>
      <div className="fade-up stagger-1 mt-9 grid gap-3 sm:grid-cols-3"><Metric label="Pipeline value" value="$184,200" delta="+12.8%"/><Metric label="Deals won" value="08" delta="+3 this month"/><Metric label="Avg. deal size" value="$23,025" delta="+8.2%"/></div>
      <div className="fade-up stagger-2 mt-10 flex flex-col justify-between gap-4 border-b border-[var(--line)] pb-4 sm:flex-row sm:items-center"><div><h2 className="font-['Space_Grotesk'] text-xl font-bold tracking-[-.03em]">Your pipeline</h2><p className="mt-1 text-sm text-[#718087]">Track and manage your active opportunities.</p></div><div className="flex gap-2"><label className="flex h-10 flex-1 items-center gap-2 rounded-lg border border-[var(--line)] bg-white px-3 text-sm text-[#8a9692] sm:w-52 sm:flex-none"><Search size={16}/><input value={search} onChange={(e) => setSearch(e.target.value)} className="w-full bg-transparent outline-none placeholder:text-[#a8b0ad]" placeholder="Search leads..." aria-label="Search leads"/></label><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--line)] bg-white text-[#718087] hover:border-[#b6c8bf] hover:text-[#172026]" aria-label="Filter leads"><Filter size={16}/></button></div></div>
      <div className="scrollbar-hide fade-up stagger-3 mt-6 grid gap-4 overflow-x-auto pb-4 md:grid-cols-2 xl:grid-cols-4">{Object.entries(visibleLeads).map(([stage, items]) => <PipelineColumn key={stage} stage={stage} items={items}/>)}</div>
      <div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-xs text-[#9aa5a1]"><span>Last synced just now</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-[#54bd83]"/> All systems operational</span></div>
    </div>} </section>
    {showAdd && <AddLead onClose={() => setShowAdd(false)}/>}</main>;
}
function Metric({ label, value, delta }: {label:string; value:string; delta:string}) { return <article className="rounded-2xl border border-[var(--line)] bg-white p-5"><p className="text-[13px] font-semibold text-[#718087]">{label}</p><div className="mt-3 flex items-end justify-between gap-2"><p className="font-['Space_Grotesk'] text-[28px] font-bold tracking-[-.04em]">{value}</p><span className="mb-1 rounded-md bg-[#e7f7ed] px-2 py-1 text-[11px] font-bold text-[#2d9766]">{delta}</span></div></article> }
function BillingWorkspace() { return <div className="mx-auto max-w-[1100px] px-5 py-8 sm:px-8 lg:px-12"><div className="fade-up"><p className="mb-2 text-sm font-semibold text-[#2d9766]">Workspace settings</p><h1 className="font-['Space_Grotesk'] text-[32px] font-bold tracking-[-.045em] sm:text-[40px]">Billing & plans</h1><p className="mt-2 text-[15px] text-[#718087]">Manage your subscription and payment details.</p></div><div className="fade-up stagger-1 mt-9 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><article className="rounded-2xl border border-[var(--line)] bg-white p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#2d9766]">Current plan</p><h2 className="mt-2 font-['Space_Grotesk'] text-2xl font-bold">Growth</h2><p className="mt-1 text-sm text-[#718087]">For teams building repeatable momentum.</p></div><span className="rounded-full bg-[#d7f2e4] px-3 py-1 text-xs font-bold text-[#20784e]">Active</span></div><div className="mt-7 flex items-end justify-between border-t border-[var(--line)] pt-5"><div><span className="font-['Space_Grotesk'] text-3xl font-bold">$79</span><span className="ml-1 text-sm text-[#718087]">/ month</span></div><button className="h-10 rounded-lg border border-[var(--line)] px-4 text-sm font-bold hover:border-[#9eb9aa] hover:bg-[#f5faf6]">Manage plan</button></div></article><article className="rounded-2xl bg-[#172026] p-6 text-white"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#d7f2e4] text-[#20784e]"><CreditCard size={17}/></div><h2 className="mt-5 font-['Space_Grotesk'] text-lg font-bold">Payment method</h2><p className="mt-2 text-sm text-[#aab9b3]">Demo mode is active. Connect Stripe to manage real payments.</p><button className="mt-6 flex h-10 items-center gap-2 rounded-lg bg-white px-4 text-sm font-bold text-[#172026] hover:bg-[#d7f2e4]">Connect Stripe <ChevronRight size={15}/></button></article></div><div className="fade-up stagger-2 mt-8 rounded-2xl border border-[var(--line)] bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-['Space_Grotesk'] text-lg font-bold">Recent invoices</h2><p className="mt-1 text-sm text-[#718087]">Your latest billing activity.</p></div><button className="text-sm font-bold text-[#2d9766] hover:text-[#20784e]">View all</button></div><div className="mt-5 divide-y divide-[#edf0ee]"><Invoice month="June 2024" amount="$79.00"/><Invoice month="May 2024" amount="$79.00"/><Invoice month="April 2024" amount="$79.00"/></div></div></div> }
function Invoice({month, amount}:{month:string;amount:string}) { return <div className="flex items-center justify-between py-4"><div><p className="text-sm font-bold">Pipeline Growth plan</p><p className="mt-1 text-xs text-[#8a9692]">{month} · Demo invoice</p></div><div className="flex items-center gap-4"><span className="text-sm font-semibold">{amount}</span><span className="rounded-md bg-[#e7f7ed] px-2 py-1 text-[11px] font-bold text-[#2d9766]">Paid</span></div></div> }
function PipelineColumn({stage, items}:{stage:string;items:Lead[]}) { return <section className="min-w-[260px] rounded-2xl bg-[#eef1ee] p-3"><div className="flex items-center justify-between px-2 pb-3"><h3 className="text-sm font-bold">{stage} <span className="ml-1 text-xs font-medium text-[#8b9792]">{items.length}</span></h3><button className="rounded-md p-1 text-[#9aa5a1] hover:bg-white hover:text-[#172026]" aria-label={`More ${stage} options`}><MoreHorizontal size={17}/></button></div><div className="space-y-3">{items.map((lead) => <article key={lead.id} className="group rounded-xl border border-[#e5eae7] bg-white p-4 shadow-[0_2px_6px_rgba(23,32,38,.025)] transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_8px_20px_rgba(23,32,38,.08)]"><div className="flex items-start justify-between"><div className="flex items-center gap-2.5"><span style={{backgroundColor:lead.color}} className="grid h-8 w-8 place-items-center rounded-full text-[10px] font-bold text-[#43504c]">{lead.initials}</span><div className="min-w-0"><p className="truncate text-[13px] font-bold">{lead.name}</p><p className="truncate text-[11px] text-[#8a9692]">{lead.company}</p></div></div><button className="rounded-md p-1 text-[#aab4b0] opacity-0 transition-opacity hover:bg-[#f3f5f3] group-hover:opacity-100" aria-label={`Actions for ${lead.name}`}><MoreHorizontal size={15}/></button></div><div className="mt-4 flex items-center justify-between border-t border-[#f0f2f0] pt-3"><span className="text-sm font-bold">{lead.value}</span><span className="text-[10px] text-[#9aa5a1]">{lead.note}</span></div></article>)}</div><button className="mt-3 flex h-9 w-full items-center justify-center gap-1 rounded-lg border border-dashed border-[#cbd4cf] text-xs font-semibold text-[#87938e] hover:border-[#8caf9e] hover:bg-white hover:text-[#2d9766]"><Plus size={14}/> Add lead</button></section> }
function AddLead({onClose}:{onClose:()=>void}) { return <div className="fixed inset-0 z-30 grid place-items-center bg-[#172026]/30 px-5 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="fade-up w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="font-['Space_Grotesk'] text-xl font-bold">Add a new lead</h2><p className="mt-1 text-sm text-[#718087]">Start tracking a new opportunity.</p></div><button onClick={onClose} className="rounded-lg p-2 text-[#718087] hover:bg-[#eef2ef]" aria-label="Close dialog"><X size={18}/></button></div><div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Name<input className="mt-2 h-11 w-full rounded-lg border border-[var(--line)] px-3 outline-none focus:border-[#70b38e]" placeholder="e.g. Jamie Smith"/></label><label className="block text-sm font-semibold">Company<input className="mt-2 h-11 w-full rounded-lg border border-[var(--line)] px-3 outline-none focus:border-[#70b38e]" placeholder="e.g. Acme Inc."/></label><label className="block text-sm font-semibold">Estimated value<input className="mt-2 h-11 w-full rounded-lg border border-[var(--line)] px-3 outline-none focus:border-[#70b38e]" placeholder="$0"/></label></div><button onClick={onClose} className="mt-6 flex h-11 w-full items-center justify-center rounded-xl bg-[#172026] text-sm font-bold text-white hover:bg-[#2c3b42]">Create lead</button></div></div> }
