"use client";

import { useEffect, useState } from "react";

function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value / 100); }
function date(value: unknown) { return new Date(String(value)).toLocaleDateString("en-US", { month: "short", day: "numeric" }); }
type Row = Record<string, string | number | null>;
type Dashboard = { accounts: Row[]; applications: Row[]; transactions: Row[]; statements: Row[] };

export default function Home() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [amount, setAmount] = useState("28.50");
  const [merchant, setMerchant] = useState("Juniper Market");
  const [application, setApplication] = useState({ fullName: "", email: "", dateOfBirth: "", annualIncome: "" });

  useEffect(() => {
    void fetch("/api/demo", { cache: "no-store" })
      .then((response) => response.json())
      .then((body) => setData(body.data))
      .catch(() => setError("Unable to load the demo ledger."));
  }, []);
  async function action(actionName: string, payload: Record<string, string> = {}) { setBusy(true); setError(""); setNotice(""); const response = await fetch("/api/demo", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, payload: { accountId: data?.accounts[0]?.id ?? "", ...payload } }) }); const body = await response.json(); if (!response.ok) setError(body.error?.message ?? "Action failed."); else { setNotice(actionName === "statement" ? "Statement generated and stored." : actionName === "authorize" && !body.data.result.allowed ? "Authorization declined and recorded." : "Action completed and persisted."); setData(body.data.dashboard); } setBusy(false); }
  if (!data) return <main><p className="muted">Loading issuer core…</p></main>;
  const account = data.accounts[0];
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">L</span><span>Ledgerline / issuer core</span></div><span className="demo-pill">Demo environment</span></header><main>
    <div className="hero"><div><p className="eyebrow">A guided account story</p><h1>From application to statement, in one clear thread.</h1><p className="lede">A simplified issuer core for showing how credit decisions, card controls, authorizations, and billing records fit together.</p></div><p className="hero-note"><strong>Demo boundary</strong><br/>Tokenized card numbers only. No network rails, real KYC, real bureau calls, PCI data, or money movement.</p></div>
    {notice && <div className="notice" role="status">{notice}</div>}{error && <div className="notice error" role="alert">{error}</div>}
    <div className="grid"><section className="panel account-card"><div className="panel-header"><div><p className="eyebrow">Primary card account</p><h2>{account.cardholder_name}</h2></div><span className="status">{account.status}</span></div><div className="card-number">{account.tokenized_number}</div><div className="balance"><small>Current balance</small>{money(Number(account.posted_balance_cents))}</div><div className="stats"><div className="stat"><small>Available</small><strong>{money(Number(account.available_credit_cents))}</strong></div><div className="stat"><small>Credit limit</small><strong>{money(Number(account.credit_limit_cents))}</strong></div><div className="stat"><small>On hold</small><strong>{money(Number(account.authorized_hold_cents))}</strong></div></div></section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Controls</p><h2>Account lifecycle</h2></div></div><p className="muted">Every action updates the persisted account record. Use this rail to drive the story.</p><div className="actions"><button className="button primary" disabled={busy || account.status === "active"} onClick={() => action("activate")}>Activate</button><button className="button" disabled={busy || account.status === "closed"} onClick={() => action(account.status === "frozen" ? "unfreeze" : "freeze")}>{account.status === "frozen" ? "Unfreeze" : "Freeze"}</button><button className="button danger" disabled={busy || account.status === "closed"} onClick={() => action("close")}>Close account</button></div><hr className="rule"/><form className="form" onSubmit={(event) => { event.preventDefault(); action("limit", { amount }); }}><label>Set credit limit<input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" /></label><button className="button" disabled={busy}>Save limit</button></form></section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Simulation lab</p><h2>Trigger a transaction</h2></div><span className="status authorized">Integer cents</span></div><form className="form" onSubmit={(event) => { event.preventDefault(); action("authorize", { amount, merchant, description: "Demo purchase" }); }}><label>Merchant<input value={merchant} onChange={(event) => setMerchant(event.target.value)} /></label><label>Amount<input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" /></label><button className="button primary" disabled={busy || account.status !== "active"}>Authorize purchase</button></form><p className="muted" style={{ marginTop: 14 }}>Frozen, closed, and over-limit attempts decline without changing posted balance.</p></section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Billing record</p><h2>Statements</h2></div><button className="button primary" disabled={busy} onClick={() => action("statement")}>Generate</button></div>{data.statements.length === 0 ? <p className="muted">No statement yet. Generate one from settled activity.</p> : <div className="list">{data.statements.map((statement) => <div className="list-row" key={statement.id}><div><div className="list-title">Period ending {date(statement.period_end)}</div><div className="list-subtitle">Due {date(statement.due_at)} · minimum due {money(Number(statement.minimum_due_cents))}</div></div><strong className="money">{money(Number(statement.balance_cents))}</strong></div>)}</div>}</section>
      <section className="panel full"><div className="panel-header"><div><p className="eyebrow">Shared record</p><h2>Recent transactions</h2></div><span className="muted">Admin + cardholder views</span></div><div className="list">{data.transactions.map((transaction) => <div className="list-row" key={transaction.id}><div><div className="list-title">{transaction.merchant_name}</div><div className="list-subtitle">{transaction.description} · {date(transaction.created_at)}</div></div><div style={{ textAlign: "right" }}><span className={`status ${transaction.status}`}>{transaction.status}</span><div className="money" style={{ marginTop: 6 }}>{money(Number(transaction.amount_cents))}</div>{transaction.status === "authorized" && <button className="button" style={{ marginTop: 8 }} onClick={() => action("settle", { transactionId: String(transaction.id) })}>Settle</button>}{transaction.status === "settled" && <button className="button" style={{ marginTop: 8 }} onClick={() => action("refund", { transactionId: String(transaction.id) })}>Refund</button>}</div></div>)}</div></section>
      <section className="panel full"><div className="panel-header"><div><p className="eyebrow">Intake</p><h2>New card application</h2></div><span className="muted">KYC stub + explainable rules</span></div><form className="form" onSubmit={(event) => { event.preventDefault(); action("apply", application).then(() => setApplication({ fullName: "", email: "", dateOfBirth: "", annualIncome: "" })); }}><div className="form-grid"><label>Full name<input required value={application.fullName} onChange={(e) => setApplication({ ...application, fullName: e.target.value })} /></label><label>Email<input required type="email" value={application.email} onChange={(e) => setApplication({ ...application, email: e.target.value })} /></label><label>Date of birth<input required type="date" value={application.dateOfBirth} onChange={(e) => setApplication({ ...application, dateOfBirth: e.target.value })} /></label><label>Annual income<input required inputMode="decimal" placeholder="75000" value={application.annualIncome} onChange={(e) => setApplication({ ...application, annualIncome: e.target.value })} /></label></div><button className="button primary" disabled={busy}>Run demo decision</button></form>{data.applications.slice(0, 3).map((item) => <div className="list-row" key={item.id}><div><div className="list-title">{item.full_name}</div><div className="list-subtitle">{item.email} · KYC {item.kyc_status}</div></div><span className={`status ${item.decision === "declined" ? "declined" : ""}`}>{item.decision}</span></div>)}</section>
    </div></main></div>;
}
